call plug#begin("~/.vim/autoload")

Plug 'preservim/nerdtree'
Plug 'evanleck/vim-svelte', {'branch': 'main'}
Plug 'itchyny/lightline.vim'
Plug 'timakro/vim-copytoggle'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/seoul256.vim'

call plug#end()

" Enable use of the mouse for all modes
set mouse=a

" Show line numbers
set number

" Only add linebreaks when I explictly hit Enter
set linebreak

" Make line wrapping obvious but not automatic
set showbreak=+++
set textwidth=0
set wrapmargin=0

" Line width warning bar on the right
set colorcolumn=121  
set visualbell

" Cursor briefly jumps to matching brace when you insert one
set showmatch

" Highlight all search matches
set hlsearch

" Use case insensitive search, except when using capital letters
set smartcase
set ignorecase
set incsearch

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set tabstop=4
set softtabstop=4

" Whitespace-ish characters
set listchars=eol:¬,tab:⇥·,trail:␠,extends:>,precedes:<,space:‧
set list

set ruler
set undolevels=1000
set backspace=indent,eol,start

set hidden

filetype plugin indent on
syntax on

set laststatus=2

" Hotkey for paste mode
set pastetoggle=<C-p>

let g:seoul256_background = 233
colo seoul256

let NERDTreeShowHidden=1

map <C-a> :NERDTreeToggle<CR>
nmap <C-c> <Plug>copytoggle

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>
